export function pytestHookSource(): string {
  return [
    "import json",
    "import os",
    "from pathlib import Path",
    "",
    "_output_path = Path(os.environ['OPCORE_PYTEST_HOOK_OUTPUT'])",
    "_selection_manifest = os.environ.get('OPCORE_PYTEST_SELECTION_MANIFEST')",
    "_selected_ids = None",
    "if _selection_manifest:",
    "    _selected_ids = set()",
    "    for line in Path(_selection_manifest).read_text(encoding='utf-8').splitlines():",
    "        line = line.strip()",
    "        if line:",
    "            _selected_ids.add(line)",
    "",
    "def _emit(payload):",
    "    with _output_path.open('a', encoding='utf-8') as handle:",
    "        handle.write(json.dumps(payload, sort_keys=True) + '\\n')",
    "",
    "def pytest_collection_modifyitems(session, config, items):",
    "    if _selected_ids is not None:",
    "        selected = [item for item in items if item.nodeid in _selected_ids]",
    "        items[:] = selected",
    "    for item in items:",
    "        _emit({'type': 'collected', 'nodeid': item.nodeid})",
    "",
    "def pytest_collectreport(report):",
    "    if report.failed:",
    "        _emit({'type': 'collect_error', 'nodeid': getattr(report, 'nodeid', ''), 'message': str(report.longrepr)})",
    "",
    "def pytest_runtest_logreport(report):",
    "    payload = {",
    "        'type': 'test_report',",
    "        'nodeid': report.nodeid,",
    "        'when': report.when,",
    "        'outcome': report.outcome",
    "    }",
    "    wasxfail = getattr(report, 'wasxfail', None)",
    "    if wasxfail is not None:",
    "        payload['wasxfail'] = str(wasxfail)",
    "    _emit(payload)",
    "",
    "def pytest_sessionfinish(session, exitstatus):",
    "    _emit({'type': 'session_finish', 'exitstatus': int(exitstatus)})"
  ].join("\n");
}
