import type { ReleaseCutoverCommandId } from "./vocabulary-01.js";
import type { ReleaseCutoverCommandExpectation} from "./vocabulary-02.js";
import { releaseCutoverRequestFilePlaceholder } from "./vocabulary-02.js";

const releaseCutoverCommandExpectations = {
  "opcore-scan": {
    canonicalCommand: ["opcore", "scan"],
    owner: "runtime",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "opcore-status": {
    canonicalCommand: ["opcore", "status"],
    owner: "runtime",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "opcore-check-changed": {
    canonicalCommand: [
      "opcore",
      "check",
      "changed",
      "--report-mode",
      "introduced",
      "--base",
      "HEAD",
      "--checks",
      "typescript.syntax",
    ],
    owner: "validation",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "opcore-measure": {
    canonicalCommand: ["opcore", "measure"],
    owner: "runtime",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "opcore-try": {
    canonicalCommand: ["opcore", "try"],
    owner: "runtime",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  status: {
    canonicalCommand: ["opcore", "status"],
    owner: "runtime",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  doctor: {
    canonicalCommand: ["opcore", "doctor"],
    owner: "runtime",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "graph-build": {
    canonicalCommand: ["opcore", "graph", "build"],
    owner: "graph",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "graph-status": {
    canonicalCommand: ["opcore", "graph", "status"],
    owner: "graph",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "graph-query": {
    canonicalCommand: ["opcore", "graph", "query"],
    owner: "graph",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "graph-impact": {
    canonicalCommand: ["opcore", "graph", "impact", "--files", "src/components/GreetingCard.tsx"],
    owner: "graph",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "graph-review-context": {
    canonicalCommand: ["opcore", "graph", "review-context", "--files", "src/components/GreetingCard.tsx"],
    owner: "graph",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "graph-detect-changes": {
    canonicalCommand: ["opcore", "graph", "detect-changes", "--files", "src/components/GreetingCard.tsx"],
    owner: "graph",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "graph-search": {
    canonicalCommand: ["opcore", "graph", "search", "Greeting", "--limit", "5"],
    owner: "graph",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "graph-serve": {
    canonicalCommand: ["opcore", "graph", "serve"],
    owner: "graph",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "inspect-symbols": {
    canonicalCommand: ["opcore", "inspect", "symbols", "Greeting", "--limit", "5"],
    owner: "inspect",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "inspect-definition": {
    canonicalCommand: ["opcore", "inspect", "definition", "GreetingCard"],
    owner: "inspect",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "inspect-references": {
    canonicalCommand: [
      "opcore",
      "inspect",
      "references",
      "function:src/components/GreetingCard.tsx#GreetingCard",
      "--limit",
      "5",
    ],
    owner: "inspect",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "inspect-signature": {
    canonicalCommand: ["opcore", "inspect", "signature", "function:src/components/GreetingCard.tsx#GreetingCard"],
    owner: "inspect",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "inspect-implementations": {
    canonicalCommand: ["opcore", "inspect", "implementations", "class:src/models.ts#GreetingModel"],
    owner: "inspect",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "inspect-search": {
    canonicalCommand: ["opcore", "inspect", "search", "Greeting", "--limit", "5"],
    owner: "inspect",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "edit-preview": {
    canonicalCommand: [
      "opcore",
      "edit",
      "exact",
      "--path",
      "src/cutover.ts",
      "--expected",
      "export const cutoverValue: number = 1;",
      "--replacement",
      "export const cutoverValue: number = 2;",
    ],
    owner: "edit",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "edit-apply": {
    canonicalCommand: [
      "opcore",
      "edit",
      "exact",
      "--path",
      "src/cutover.ts",
      "--expected",
      "export const cutoverValue: number = 1;",
      "--replacement",
      "export const cutoverValue: number = 2;",
      "--apply",
    ],
    owner: "edit",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "edit-refused": {
    canonicalCommand: [
      "opcore",
      "edit",
      "exact",
      "--path",
      "src/cutover.ts",
      "--expected",
      "export const cutoverValue: number = 2;",
      "--replacement",
      "export const cutoverValue: number = missingCutoverSymbol;",
      "--apply",
    ],
    owner: "edit",
    status: "error",
    exitCode: 1,
    bin: "opcore",
  },
  "check-files": {
    canonicalCommand: ["opcore", "check", "files", "src/cutover.ts", "--checks", "typescript.syntax,typescript.types"],
    owner: "validation",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "validate-request": {
    canonicalCommand: ["opcore", "validate", "request", "--request-file", releaseCutoverRequestFilePlaceholder],
    requestFileBasename: "validate-request.json",
    owner: "validation",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "validate-pre-write-pass": {
    canonicalCommand: [
      "opcore",
      "validate",
      "pre-write",
      "--request-file",
      releaseCutoverRequestFilePlaceholder,
      "--timeout-ms",
      "30000",
    ],
    requestFileBasename: "pre-write-pass.json",
    owner: "validation",
    status: "ok",
    exitCode: 0,
    bin: "opcore",
  },
  "validate-pre-write-fail": {
    canonicalCommand: [
      "opcore",
      "validate",
      "pre-write",
      "--request-file",
      releaseCutoverRequestFilePlaceholder,
      "--timeout-ms",
      "30000",
    ],
    requestFileBasename: "pre-write-fail.json",
    owner: "validation",
    status: "error",
    exitCode: 1,
    bin: "opcore",
  },
} as const satisfies Record<ReleaseCutoverCommandId, ReleaseCutoverCommandExpectation>;

export { releaseCutoverCommandExpectations };
